steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - -t
      - europe-west1-docker.pkg.dev/$PROJECT_ID/toonexpo/toonexpo-api:latest
      - .

images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/toonexpo/toonexpo-api:latest

options:
  logging: CLOUD_LOGGING_ONLY
