import type { PortalReadinessAssessmentItem } from '@toonexpo/contracts';

/**
 * Sample builder readiness assessment for empty-state UI preview.
 * Not persisted — shown only when the portal has no real assessments yet.
 */
export const BUILDER_READINESS_PREVIEW_ASSESSMENT: PortalReadinessAssessmentItem = {
  id: 'preview-assessment',
  targetType: 'project',
  projectId: 'preview-project',
  projectName: 'Sunrise Residences',
  coverUrl: null,
  status: 'in_progress',
  overallScore: 68,
  lastEvaluatedAt: '2026-08-01T10:00:00.000Z',
  scores: [
    {
      categoryId: 'preview-product',
      categoryCode: 'product',
      categoryName: 'Product',
      categoryWeight: 40,
      score: 72,
      status: 'in_progress',
      recommendationSummary: 'Add clearer price orientation and highlight the special offer.',
      serviceProviderCategoryId: null,
      helpAvailable: false,
      criteria: [
        {
          criterionId: 'c-price',
          code: 'price_orientation',
          parentId: null,
          maxPoints: 10,
          sortOrder: 1,
          value: 7,
          checked: true,
          percent: 70,
          children: [],
        },
        {
          criterionId: 'c-purpose',
          code: 'property_purpose',
          parentId: null,
          maxPoints: 10,
          sortOrder: 2,
          value: 8,
          checked: true,
          percent: 80,
          children: [],
        },
        {
          criterionId: 'c-offer',
          code: 'special_offer',
          parentId: null,
          maxPoints: 5,
          sortOrder: 3,
          value: 3,
          checked: true,
          percent: 60,
          children: [],
        },
        {
          criterionId: 'c-payment',
          code: 'payment_methods',
          parentId: null,
          maxPoints: null,
          sortOrder: 4,
          value: null,
          checked: true,
          percent: null,
          children: [
            {
              criterionId: 'c-prepay',
              code: 'prepayment',
              parentId: 'c-payment',
              maxPoints: null,
              sortOrder: 1,
              value: null,
              checked: true,
              percent: null,
              children: [],
            },
            {
              criterionId: 'c-mortgage',
              code: 'mortgage_option',
              parentId: 'c-payment',
              maxPoints: null,
              sortOrder: 2,
              value: null,
              checked: true,
              percent: null,
              children: [],
            },
            {
              criterionId: 'c-installment',
              code: 'installment_option',
              parentId: 'c-payment',
              maxPoints: null,
              sortOrder: 3,
              value: null,
              checked: false,
              percent: null,
              children: [],
            },
          ],
        },
      ],
    },
    {
      categoryId: 'preview-packaging',
      categoryCode: 'packaging',
      categoryName: 'Packaging',
      categoryWeight: 35,
      score: 55,
      status: 'needs_improvement',
      recommendationSummary: 'Upload renders and interactive apartment materials before the expo.',
      serviceProviderCategoryId: null,
      helpAvailable: true,
      criteria: [
        {
          criterionId: 'c-media',
          code: 'media_materials',
          parentId: null,
          maxPoints: null,
          sortOrder: 1,
          value: null,
          checked: true,
          percent: null,
          children: [
            {
              criterionId: 'c-videos',
              code: 'videos',
              parentId: 'c-media',
              maxPoints: 10,
              sortOrder: 1,
              value: 4,
              checked: true,
              percent: 40,
              children: [],
            },
            {
              criterionId: 'c-renders',
              code: 'renders',
              parentId: 'c-media',
              maxPoints: 10,
              sortOrder: 2,
              value: 6,
              checked: true,
              percent: 60,
              children: [],
            },
            {
              criterionId: 'c-apt-int',
              code: 'apartment_interactive',
              parentId: 'c-media',
              maxPoints: 10,
              sortOrder: 3,
              value: 5,
              checked: true,
              percent: 50,
              children: [],
            },
          ],
        },
        {
          criterionId: 'c-digital',
          code: 'digital_presence',
          parentId: null,
          maxPoints: 10,
          sortOrder: 2,
          value: 7,
          checked: true,
          percent: 70,
          children: [],
        },
      ],
    },
    {
      categoryId: 'preview-team',
      categoryCode: 'team',
      categoryName: 'Team',
      categoryWeight: 25,
      score: 80,
      status: 'ready',
      recommendationSummary: null,
      serviceProviderCategoryId: null,
      helpAvailable: false,
      criteria: [
        {
          criterionId: 'c-mkt',
          code: 'marketing_team',
          parentId: null,
          maxPoints: 10,
          sortOrder: 1,
          value: 8,
          checked: true,
          percent: 80,
          children: [],
        },
        {
          criterionId: 'c-sales',
          code: 'sales_team',
          parentId: null,
          maxPoints: 10,
          sortOrder: 2,
          value: 8,
          checked: true,
          percent: 80,
          children: [],
        },
      ],
    },
  ],
  requiredActions: [
    {
      id: 'preview-action-1',
      title: 'Upload project renders',
      description: 'Add at least 6 high-resolution exterior and lobby renders.',
      status: 'open',
      scoreId: 'preview-packaging',
      relatedEntityType: null,
      relatedEntityId: null,
    },
    {
      id: 'preview-action-2',
      title: 'Enable installment option',
      description: 'Publish installment terms on the project page.',
      status: 'in_progress',
      scoreId: 'preview-product',
      relatedEntityType: null,
      relatedEntityId: null,
    },
    {
      id: 'preview-action-3',
      title: 'Confirm sales desk staffing',
      description: null,
      status: 'done',
      scoreId: 'preview-team',
      relatedEntityType: null,
      relatedEntityId: null,
    },
  ],
  recommendations: [
    {
      id: 'preview-rec-1',
      title: 'Prioritize packaging',
      description:
        'Media quality has the biggest lift on your score before the exhibition opens.',
      sortOrder: 1,
      scoreId: 'preview-packaging',
    },
    {
      id: 'preview-rec-2',
      title: 'Complete payment options',
      description: 'Buyers expect mortgage and installment clarity next to pricing.',
      sortOrder: 2,
      scoreId: 'preview-product',
    },
  ],
};
