export {
  APARTMENT_STATUSES,
  DEAL_ACTIVITY_TYPES,
  DEAL_STAGES,
  PARTNER_TYPES,
  PLATFORM_ROLES,
  PUBLICATION_STATUSES,
  QR_SCAN_PURPOSES,
  REQUEST_SOURCES,
  type ApartmentStatus,
  type DealActivityType,
  type DealStage,
  type PartnerType,
  type PlatformRole,
  type PublicationStatus,
  type QrScanPurpose,
  type RequestSource,
} from './enums';
