/**
 * Health check response returned by NestJS `/api/v1/health`.
 */
export type HealthResponse = {
  status: 'ok' | 'degraded' | 'error';
  service: string;
  timestamp: string;
};

/**
 * API version prefix used by NestJS controllers.
 */
export const API_V1_PREFIX = '/api/v1' as const;

export {
  CHANGE_PASSWORD_ERROR_CODES,
  CSRF_COOKIE_NAME,
  CSRF_HEADER_NAME,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PROFILE_NAME_MAX_LENGTH,
  PROFILE_PHONE_MAX_LENGTH,
  changePasswordRequestSchema,
  passwordFieldSchema,
  updateProfileRequestSchema,
} from './auth.js';

export type {
  AccountType,
  AuthSessionResponse,
  ChangePasswordErrorCode,
  ChangePasswordRequest,
  ChangePasswordResponse,
  CompanyMemberRole,
  CompanyMemberStatus,
  CompanyType,
  CsrfTokenResponse,
  ForgotPasswordRequest,
  ForgotPasswordResponse,
  LoginRequest,
  RegisterRequest,
  UpdateProfileRequest,
  UserResponse,
  UserStatus,
} from './auth.js';

export type {
  ApartmentAvailabilitySummary,
  ApartmentDetail,
  ApartmentPriceOverlayItem,
  ApartmentSalesStatus,
  BuilderDetail,
  BuilderSummary,
  BuildingDetail,
  BuildingSummary,
  CatalogProjectRef,
  FloorDetail,
  FloorApartmentSummary,
  FloorSummary,
  ListProjectsQuery,
  MediaAssetSummary,
  PaginatedResponse,
  PriceVisibility,
  ProjectDetail,
  ProjectListItem,
  ProjectPriceRangeOverlay,
  ProjectPriceRangeOverlayListResponse,
  ProjectPricesOverlay,
  PublicationStatus,
} from './catalog.js';

export type {
  AdminCompanyProjectListItem,
  AdminCompanyProjectListResponse,
  AdminProjectListItem,
  AdminProjectListResponse,
  AdminProjectScope,
  AdminBuildingListItem,
  AdminBuildingListResponse,
  AdminFloorListItem,
  AdminFloorListResponse,
  AdminApartmentListItem,
  AdminApartmentListResponse,
  AdminBuildingInventoryFloor,
  AdminBuildingInventoryGlance,
  CompanyListResponse,
  CompanyMemberListResponse,
  CompanyMemberResponse,
  CompanyProfileResponse,
  CompanyResponse,
  CompanySource,
  CompanyStatus,
  CreateCompanyRequest,
  InviteCompanyMemberRequest,
  ProvisionCompanyResponse,
  SetPasswordRequest,
  UpdateCompanyMemberRequest,
  UpdateCompanyProfileRequest,
  UpdateCompanyRequest,
} from './companies.js';

export type {
  BulkCreatePortalApartmentsRequest,
  CreatePortalApartmentRequest,
  CreatePortalBuildingRequest,
  CreatePortalFloorRequest,
  CreatePortalProjectRequest,
  LocaleTextMap,
  PortalApartmentDetail,
  PortalApartmentStatusHistoryItem,
  PortalBuildingSummary,
  PortalFloorSummary,
  PortalProjectDetail,
  PortalProjectListItem,
  PortalProjectListResponse,
  PortalTranslationsInput,
  UpdatePortalApartmentRequest,
  UpdatePortalBuildingRequest,
  UpdatePortalFloorRequest,
  UpdatePortalProjectRequest,
  UpdatePortalPublicationRequest,
} from './portal.js';

export type {
  BuyerQrResponse,
  BuyerQrScanHistoryItem,
  BuyerQrScanHistoryResponse,
  ProjectQrResponse,
  QrBuyerActionPayload,
  QrBuyerIdentity,
  QrCodeStatus,
  QrEntranceCheckinPayload,
  QrOwnerProfilePayload,
  QrResolveKind,
  QrResolveResponse,
  QrScanContext,
  QrScanResultStatus,
  ResolveQrRequest,
} from './qr.js';

export type {
  AttachCrmDealApartmentBody,
  BuyerFacingRequestStatus,
  BuyerRequestListItem,
  BuyerRequestListResponse,
  CreateBuyerRequestBody,
  CreateCrmActivityBody,
  CreateCrmNoteBody,
  CreateDealFromScanBody,
  CreateManualDealBody,
  CreateAdminManualDealBody,
  CrmActivityItem,
  CrmActivityStatus,
  CrmActivityType,
  CrmApartmentLinkItem,
  CrmBuyerContact,
  CrmDealApartmentLinkType,
  CrmDealDetail,
  CrmDealListItem,
  ListCrmDealsQuery,
  CrmDealListResponse,
  CrmDealStatus,
  CrmNoteItem,
  CrmNoteVisibility,
  CrmRequestHistoryItem,
  IntakeCreateResult,
  RequestSource,
  RequestStatus,
  UpdateCrmActivityBody,
  UpdateCrmDealBody,
} from './crm.js';

export type {
  CreateReadinessAssessmentBody,
  CreateReadinessCategoryBody,
  CreateReadinessInternalNoteBody,
  CreateReadinessRecommendationBody,
  CreateReadinessRequiredActionBody,
  PortalReadinessAssessmentItem,
  PortalReadinessRecommendationItem,
  PortalReadinessRequiredActionItem,
  PortalReadinessResponse,
  PortalReadinessScoreItem,
  ReadinessAssessmentDetail,
  ReadinessAssessmentListItem,
  ReadinessAssessmentListResponse,
  ReadinessAssessmentTargetType,
  ReadinessCategoryItem,
  ReadinessCategoryListResponse,
  ReadinessInternalNoteItem,
  ReadinessRecommendationItem,
  ReadinessRequiredActionItem,
  ReadinessRequiredActionStatus,
  ReadinessScoreItem,
  ReadinessScoreStatus,
  ReadinessVisibility,
  UpdateReadinessAssessmentBody,
  UpdateReadinessCategoryBody,
  UpdateReadinessRecommendationBody,
  UpdateReadinessRequiredActionBody,
  UpsertReadinessScoreBody,
} from './readiness.js';

export type {
  AdminPartnerDetail,
  AdminPartnerListItem,
  AdminPartnerListResponse,
  CreateAdminPartnerBody,
  CreatePartnerOfferBody,
  PartnerCompanyStatus,
  PartnerCompanyType,
  PartnerContacts,
  PartnerOfferItem,
  PartnerOfferTranslationsInput,
  PartnerProfileTranslationsInput,
  PartnerSocialLinks,
  PortalPartnerDetail,
  PublicPartnerDetail,
  PublicPartnerListItem,
  PublicPartnerListResponse,
  PublicPartnerOfferItem,
  UpdateAdminPartnerBody,
  UpdatePartnerOfferBody,
  UpdatePortalPartnerBody,
} from './partners.js';

export type {
  BankOfferListItem,
  BankOfferListResponse,
  CreateBankOfferBody,
  MortgageCalculatorInput,
  MortgageCalculatorOfferSummary,
  MortgageCalculatorResult,
  PortalCreateBankOfferBody,
  PortalUpdateBankOfferBody,
  PublicMortgageBankSummary,
  PublicMortgageOfferItem,
  PublicMortgageOfferListResponse,
  UpdateBankOfferBody,
} from './mortgage.js';

export type {
  ActiveEventResponse,
  BoothAssignmentDetail,
  BoothAssignmentListResponse,
  BoothAssignmentSummary,
  BoothListResponse,
  BoothSearchResponse,
  BoothSearchResult,
  BoothSummary,
  BoothType,
  BuyerCheckInActiveEventSummary,
  BuyerCheckInCurrentStatus,
  BuyerCheckInHistoryItem,
  BuyerCheckInStatusResponse,
  CheckInDayBreakdown,
  CheckInScanRequest,
  CheckInScanResponse,
  CheckInStatus,
  CheckInSummaryResponse,
  CreateBoothAssignmentRequest,
  CreateBoothRequest,
  CreateEventRequest,
  CreateVenueMapRequest,
  CurrentEventResponse,
  EventListResponse,
  EventStatus,
  EventSummary,
  PublicBoothAssignment,
  PublicBoothDetail,
  PublicBoothListResponse,
  PublicEntranceNode,
  PublicEntranceNodeListResponse,
  PublicVenueMapSummary,
  RecentCheckInItem,
  RecentCheckInResponse,
  RouteEdgeInput,
  RouteEdgeSummary,
  RouteGraphPayload,
  RouteGraphResponse,
  RouteNodeInput,
  RouteNodeSummary,
  RouteNodeType,
  RoutePathNode,
  RoutePathResponse,
  UpdateBoothAssignmentRequest,
  UpdateBoothRequest,
  UpdateEventRequest,
  UpdateVenueMapRequest,
  VenueMapListResponse,
  VenueMapSummary,
} from './exhibition.js';

export type {
  AdminAnalyticsOverview,
  AnalyticsDateRange,
  AnalyticsEventType,
  ApartmentSalesStatusSummary,
  BuilderReadinessSummary,
  CheckInSummary,
  EntityFavoriteCount,
  EntityViewCount,
  FavoritesSummary,
  PlatformActivitySummary,
  PortalAnalyticsOverview,
  QrScanContextCount,
  ReadinessCategoryAverage,
  SourceCount,
  StatusCount,
} from './analytics.js';

export type {
  BuyerFavoritesListResponse,
  BuyerFavoritesStatusResponse,
  FavoriteApartmentCard,
  FavoriteApartmentListItem,
  FavoriteListItem,
  FavoriteProjectListItem,
  FavoriteTargetType,
} from './favorites.js';

export type {
  AdminServiceProviderItem,
  AdminServiceProviderListResponse,
  CreateServiceProviderBody,
  CreateServiceProviderCategoryBody,
  PortalServiceProviderItem,
  PortalServiceProviderListResponse,
  ServiceProviderCategoryItem,
  ServiceProviderCategoryListResponse,
  ServiceProviderCategoryRef,
  ServiceProviderType,
  UpdateServiceProviderBody,
  UpdateServiceProviderCategoryBody,
} from './service-providers.js';

export type {
  AdminBosProvisioningDetail,
  AdminBosProvisioningListItem,
  AdminBosProvisioningListResponse,
  BosProvisioningCompanyType,
  BosProvisioningRequestBody,
  BosProvisioningResponse,
  BosProvisioningStatus,
  BosProvisioningWireStatus,
  BosRequestedModule,
  IntegrationAuditAction,
  IntegrationAuditLogItem,
} from './integrations.js';

export type {
  CreatePortalVisualCanvasRequest,
  CreatePortalVisualHotspotRequest,
  PortalVisualCanvasDetail,
  PortalVisualCanvasListItem,
  PortalVisualCanvasListResponse,
  PortalVisualHotspotItem,
  PublicVisualCanvasItem,
  PublicVisualCanvasListResponse,
  PublicVisualHotspotItem,
  PublicVisualMapMedia,
  UpdatePortalVisualCanvasRequest,
  UpdatePortalVisualHotspotRequest,
  VisualHotspotTargetStatus,
  VisualHotspotTargetType,
  VisualMapContextType,
} from './visual-map.js';

export type { ListMediaQuery, MediaAssetItem, MediaListResponse } from './media.js';
